### ISSUE TITLE
Backend functionality for framing service

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/graphframing-service#1]
Functionality described at: https://github.com/ATTX-project/ATTX-project.github.io/blob/dev/attx_project/Dissemination-Workflow.md

**Comment by blankdots** [comment]
example message:
```json
{
	  "provenance": {
	    "context": {
	      "workflowID": "ingestionwf",
	      "activityID": 1,
	      "stepID": "replaceds"
	    }
	  },
     "payload": {
        "framingServiceInput": {
            "docType": "test",
            "ldFrame": "Data",
            "sourceData":
            [
              {
                "inputType": "URI",
                "contentType": "text/turtle",
                "input": "file:///graph-data.ttl"
              }
            ]
          }
        }}
```
MIME type for the file is not required however it will default to Turtle format if no other format is specified.
if the protocol in the input is http or https it will try to retrieve the data from the Graph Store using the GraphManager Service, otherwise it will fail.

**Comment by blankdots** [comment]
example request inspired by the examples in json-ld.org/playground
```json
{
	  "provenance": {
	    "context": {
	      "workflowID": "ingestionwf",
	      "activityID": 1,
	      "stepID": "replaceds"
	    }
	  },
     "payload": {
        "framingServiceInput": {
            "docType": "test",
            "ldFrame": "{\r\n  \"@context\": {\r\n    \"dc\": \"http:\/\/purl.org\/dc\/elements\/1.1\/\",\r\n    \"ex\": \"http:\/\/example.org\/vocab#\"\r\n  },\r\n  \"@type\": \"ex:Library\",\r\n  \"ex:contains\": {\r\n    \"@type\": \"ex:Book\",\r\n    \"ex:contains\": {\r\n      \"@type\": \"ex:Chapter\"\r\n    }\r\n  }\r\n}",
            "sourceData":
            [
              {
                "inputType": "URI",
                "contentType": "text/turtle",
                "input": "file:///attx-sb-shared/graph-data.ttl"
              },
              {
                "inputType": "Graph",
                "input": "http://example.org/books"
              }
            ]
          }
        }}
```

**Comment by blankdots** [comment]
Minimal configuration:
```yml
version: '2'
services:
  messagebroker:
    image: rabbitmq:3.6.12-management
    ports:
      - '4369:4369'
      - '5671:5671'
      - '5672:5672'
      - '15671:15671'
      - '15672:15672'
      - '25672:25672'
    environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=password
  fuseki:
    image: attxproject/attx-fuseki:fuseki3.4.0
    environment:
      - ADMIN_PASSWORD=pw123
    ports:
      - 3030:3030
  graphmanager:
    image: attx-dev:5000/gm-api:latest
    ports:
      - 4302:4302
    depends_on:
      - messagebroker
    environment:
      - MHOST=messagebroker
      - GHOST=fuseki
    links:
      - messagebroker:messagebroker
  ldframe:
    image: attx-dev:5000/ldframe-service:latest
    ports:
      - 4303:4303
    depends_on:
      - messagebroker
    environment:
      - MHOST=messagebroker
      - GMHOST=graphmanager
    links:
      - graphmanager:graphmanager
      - messagebroker:messagebroker
 
```
